// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Backend.Models.Data
{
    public partial class CategoryProduct
    {
        public CategoryProduct()
        {
            Product = new HashSet<Product>();
        }

        public int Id { get; set; }
        public int? IdSeller { get; set; }
        public string CategoryName { get; set; }

        public virtual Seller IdSellerNavigation { get; set; }
        public virtual ICollection<Product> Product { get; set; }
    }
}