// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Backend.Models.Data
{
    public partial class DataAddress
    {
        public DataAddress()
        {
            Address = new HashSet<Address>();
        }

        public string Id { get; set; }
        public string AddressData { get; set; }
        public string AddressDetail { get; set; }
        public string UserName { get; set; }
        public string TelUser { get; set; }

        public virtual ICollection<Address> Address { get; set; }
    }
}