// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Backend.Models.Data
{
    public partial class Delivery
    {
        public int Id { get; set; }
        public string IdOrder { get; set; }
        public int? IdStatusDelivery { get; set; }
        public DateTime? Date { get; set; }

        public virtual Order IdOrderNavigation { get; set; }
        public virtual StatusDelivery IdStatusDeliveryNavigation { get; set; }
    }
}