// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Backend.Models.Data
{
    public partial class DetailProduct
    {
        public string Id { get; set; }
        public int? IdProduct { get; set; }
        public string Image { get; set; }
        public string Weight { get; set; }
        public string DataMore { get; set; }
        public string Size { get; set; }

        public virtual Product IdProductNavigation { get; set; }
    }
}