// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Backend.Models.Data
{
    public partial class List
    {
        public List()
        {
            Review = new HashSet<Review>();
        }

        public string Id { get; set; }
        public string IdOrder { get; set; }
        public int? IdProduct { get; set; }
        public int? PriceProduct { get; set; }
        public int? NumberProduct { get; set; }

        public virtual Order IdOrderNavigation { get; set; }
        public virtual Product IdProductNavigation { get; set; }
        public virtual ICollection<Review> Review { get; set; }
    }
}