// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Backend.Models.Data
{
    public partial class OrderProduct
    {
        public OrderProduct()
        {
            ProductAdded = new HashSet<ProductAdded>();
        }

        public int Id { get; set; }
        public int? IdSeller { get; set; }
        public int? Number { get; set; }
        public bool? Status { get; set; }
        public DateTime? Date { get; set; }

        public virtual Seller IdSellerNavigation { get; set; }
        public virtual ICollection<ProductAdded> ProductAdded { get; set; }
    }
}