// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Backend.Models.Data
{
    public partial class Order
    {
        public Order()
        {
            Delivery = new HashSet<Delivery>();
            List = new HashSet<List>();
        }

        public string Id { get; set; }
        public bool? StatusMoney { get; set; }
        public string ProofTransfer { get; set; }
        public DateTime? Date { get; set; }
        public int? PriceTotal { get; set; }
        public bool? StatusForUser { get; set; }
        public string IdAddress { get; set; }

        public virtual Address IdAddressNavigation { get; set; }
        public virtual ICollection<Delivery> Delivery { get; set; }
        public virtual ICollection<List> List { get; set; }
    }
}