// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Backend.Models.Data
{
    public partial class ProductAdded
    {
        public int Id { get; set; }
        public int? IdOrderProduct { get; set; }
        public int? IdProduct { get; set; }

        public virtual OrderProduct IdOrderProductNavigation { get; set; }
        public virtual Product IdProductNavigation { get; set; }
    }
}