// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Backend.Models.Data
{
    public partial class Product
    {
        public Product()
        {
            DetailProduct = new HashSet<DetailProduct>();
            List = new HashSet<List>();
            ProductAdded = new HashSet<ProductAdded>();
        }

        public int Id { get; set; }
        public int? IdCategoryProduct { get; set; }
        public string Name { get; set; }
        public int? Price { get; set; }
        public int? Stock { get; set; }
        public string Color { get; set; }
        public string Image { get; set; }

        public virtual CategoryProduct IdCategoryProductNavigation { get; set; }
        public virtual ICollection<DetailProduct> DetailProduct { get; set; }
        public virtual ICollection<List> List { get; set; }
        public virtual ICollection<ProductAdded> ProductAdded { get; set; }
    }
}