// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Backend.Models.Data
{
    public partial class Review
    {
        public string Id { get; set; }
        public string IdList { get; set; }
        public string Data { get; set; }
        public DateTime? Date { get; set; }
        public string Image { get; set; }

        public virtual List IdListNavigation { get; set; }
    }
}